package com.turboagile.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Architecture Diagram Entity
 * Represents an architecture diagram generated by the wizard
 * 
 * @author TurboAgile Team
 * @version 2.0.0
 */
@Entity
@Table(name = "architecture_diagrams", schema = "turboagile")
public class ArchitectureDiagram extends BaseEntity {

    @NotBlank(message = "Diagram name is required")
    @Size(min = 3, max = 255, message = "Diagram name must be between 3 and 255 characters")
    @Column(name = "name", nullable = false)
    private String name;

    @Size(max = 1000, message = "Description cannot exceed 1000 characters")
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "diagram_type", nullable = false)
    private DiagramType diagramType;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private DiagramStatus status = DiagramStatus.DRAFT;

    @Column(name = "content", columnDefinition = "TEXT")
    private String content; // JSON or XML content of the diagram

    @Column(name = "image_url")
    private String imageUrl; // URL to the generated image

    @Column(name = "svg_content", columnDefinition = "TEXT")
    private String svgContent; // SVG content for vector graphics

    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    @Column(name = "last_modified")
    private LocalDateTime lastModified;

    @Column(name = "diagram_version")
    private Integer diagramVersion = 1;

    @Column(name = "tags", columnDefinition = "TEXT[]")
    private String[] tags;

    @Column(name = "metadata", columnDefinition = "JSONB")
    private String metadata; // Additional metadata in JSON format

    @Column(name = "generation_parameters", columnDefinition = "JSONB")
    private String generationParameters; // Parameters used to generate the diagram

    @Column(name = "quality_score")
    private Double qualityScore; // AI-generated quality score

    @Column(name = "review_notes", columnDefinition = "TEXT")
    private String reviewNotes;

    @Column(name = "approved_by")
    private String approvedBy;

    @Column(name = "approved_at")
    private LocalDateTime approvedAt;

    // Relationships
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_user")
    private User createdByUser;

    @OneToMany(mappedBy = "architectureDiagram", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Set<DiagramVersion> versions = new HashSet<>();

    // Constructors
    public ArchitectureDiagram() {}

    public ArchitectureDiagram(String name, String description, DiagramType diagramType, Project project) {
        this.name = name;
        this.description = description;
        this.diagramType = diagramType;
        this.project = project;
        this.generatedAt = LocalDateTime.now();
        this.lastModified = LocalDateTime.now();
    }

    // Getters and Setters
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public DiagramType getDiagramType() {
        return diagramType;
    }

    public void setDiagramType(DiagramType diagramType) {
        this.diagramType = diagramType;
    }

    public DiagramStatus getStatus() {
        return status;
    }

    public void setStatus(DiagramStatus status) {
        this.status = status;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getSvgContent() {
        return svgContent;
    }

    public void setSvgContent(String svgContent) {
        this.svgContent = svgContent;
    }

    public LocalDateTime getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(LocalDateTime generatedAt) {
        this.generatedAt = generatedAt;
    }

    public LocalDateTime getLastModified() {
        return lastModified;
    }

    public void setLastModified(LocalDateTime lastModified) {
        this.lastModified = LocalDateTime.now();
    }

    public Integer getDiagramVersion() {
        return diagramVersion;
    }

    public void setDiagramVersion(Integer diagramVersion) {
        this.diagramVersion = diagramVersion;
    }

    public String[] getTags() {
        return tags;
    }

    public void setTags(String[] tags) {
        this.tags = tags;
    }

    public String getMetadata() {
        return metadata;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    public String getGenerationParameters() {
        return generationParameters;
    }

    public void setGenerationParameters(String generationParameters) {
        this.generationParameters = generationParameters;
    }

    public Double getQualityScore() {
        return qualityScore;
    }

    public void setQualityScore(Double qualityScore) {
        this.qualityScore = qualityScore;
    }

    public String getReviewNotes() {
        return reviewNotes;
    }

    public void setReviewNotes(String reviewNotes) {
        this.reviewNotes = reviewNotes;
    }

    public String getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    public LocalDateTime getApprovedAt() {
        return approvedAt;
    }

    public void setApprovedAt(LocalDateTime approvedAt) {
        this.approvedAt = approvedAt;
    }

    // Relationship getters and setters
    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public User getCreatedByUser() {
        return createdByUser;
    }

    public void setCreatedByUser(User createdByUser) {
        this.createdByUser = createdByUser;
    }

    public Set<DiagramVersion> getVersions() {
        return versions;
    }

    public void setVersions(Set<DiagramVersion> versions) {
        this.versions = versions;
    }

    // Business methods
    public boolean isDraft() {
        return status == DiagramStatus.DRAFT;
    }

    public boolean isInReview() {
        return status == DiagramStatus.IN_REVIEW;
    }

    public boolean isApproved() {
        return status == DiagramStatus.APPROVED;
    }

    public boolean isRejected() {
        return status == DiagramStatus.REJECTED;
    }

    public boolean isArchived() {
        return status == DiagramStatus.ARCHIVED;
    }

    public void submitForReview() {
        this.status = DiagramStatus.IN_REVIEW;
        this.lastModified = LocalDateTime.now();
    }

    public void approve(String approvedBy) {
        this.status = DiagramStatus.APPROVED;
        this.approvedBy = approvedBy;
        this.approvedAt = LocalDateTime.now();
        this.lastModified = LocalDateTime.now();
    }

    public void reject(String reviewNotes) {
        this.status = DiagramStatus.REJECTED;
        this.reviewNotes = reviewNotes;
        this.lastModified = LocalDateTime.now();
    }

    public void archive() {
        this.status = DiagramStatus.ARCHIVED;
        this.lastModified = LocalDateTime.now();
    }

    public void addTag(String tag) {
        if (this.tags == null) {
            this.tags = new String[0];
        }
        String[] newTags = new String[this.tags.length + 1];
        System.arraycopy(this.tags, 0, newTags, 0, this.tags.length);
        newTags[this.tags.length] = tag;
        this.tags = newTags;
    }

    public boolean hasTag(String tag) {
        if (this.tags == null) {
            return false;
        }
        for (String t : this.tags) {
            if (t.equals(tag)) {
                return true;
            }
        }
        return false;
    }

    public void incrementVersion() {
        this.diagramVersion++;
        this.lastModified = LocalDateTime.now();
    }

    public boolean isHighQuality() {
        return qualityScore != null && qualityScore >= 8.0;
    }

    public boolean isMediumQuality() {
        return qualityScore != null && qualityScore >= 6.0 && qualityScore < 8.0;
    }

    public boolean isLowQuality() {
        return qualityScore != null && qualityScore < 6.0;
    }

    @Override
    public String toString() {
        return "ArchitectureDiagram{" +
                "id=" + getId() +
                ", name='" + name + '\'' +
                ", diagramType=" + diagramType +
                ", status=" + status +
                ", diagramVersion=" + diagramVersion +
                ", isActive=" + isActive() +
                '}';
    }

    // Diagram Type Enum
    public enum DiagramType {
        SEQUENCE("Sequence Diagram", "Shows interactions between components over time"),
        ER("Entity Relationship", "Database schema and relationships"),
        COMPONENT("Component Diagram", "System components and their dependencies"),
        CLASS("Class Diagram", "Object-oriented class structure"),
        ACTIVITY("Activity Diagram", "Workflow and process flow"),
        STATE("State Diagram", "State transitions of objects"),
        DEPLOYMENT("Deployment Diagram", "System deployment architecture"),
        NETWORK("Network Diagram", "Network topology and connections"),
        INFRASTRUCTURE("Infrastructure", "System infrastructure layout"),
        CUSTOM("Custom Diagram", "Custom diagram type");

        private final String displayName;
        private final String description;

        DiagramType(String displayName, String description) {
            this.displayName = displayName;
            this.description = description;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getDescription() {
            return description;
        }
    }

    // Diagram Status Enum
    public enum DiagramStatus {
        DRAFT("Draft", "Diagram is in draft state"),
        IN_REVIEW("In Review", "Diagram is under review"),
        APPROVED("Approved", "Diagram has been approved"),
        REJECTED("Rejected", "Diagram has been rejected"),
        ARCHIVED("Archived", "Diagram has been archived");

        private final String displayName;
        private final String description;

        DiagramStatus(String displayName, String description) {
            this.displayName = displayName;
            this.description = description;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getDescription() {
            return description;
        }
    }
}
